// Reviewed meaning illustrations. Cells are ordered left to right, top to bottom.
import type { Concept } from "@/types";
export const meaningSheets = {
  states: [
    "sad",
    "happy",
    "empty",
    "full",
    "wet",
    "dry",
    "clean",
    "dirty",
    "sleepy",
    "hungry",
    "thirsty",
    "same",
    "different",
    "big",
    "small",
    "long",
  ],
  properties: [
    "short",
    "tall",
    "heavy",
    "light-weight",
    "hot",
    "cold",
    "warm",
    "cool",
    "soft",
    "hard",
    "smooth",
    "rough",
    "loud",
    "quiet",
    "fast",
    "slow",
  ],
  colors: [
    "red",
    "blue",
    "green",
    "yellow",
    "black",
    "white",
    "pink",
    "purple",
    "brown",
    "gray",
    "round",
    "orange-color",
    "colorful",
    "light-color",
    "dark-color",
    "park",
  ],
  "actions-a": [
    "eat",
    "drink",
    "run",
    "walk",
    "jump",
    "sleep",
    "sit",
    "stand",
    "open",
    "close",
    "wash",
    "drive",
    "clap",
    "wave",
    "hug",
    "read",
  ],
  "actions-b": [
    "draw",
    "play",
    "kick",
    "throw",
    "look",
    "listen",
    "point",
    "smile",
    "laugh",
    "cry",
    "help",
    "give",
    "take",
    "bring",
    "carry",
    "push",
  ],
  "actions-c": [
    "pull",
    "roll",
    "catch",
    "bounce",
    "climb",
    "crawl",
    "dance",
    "sing",
    "count",
    "build",
    "stack",
    "paint",
    "cut",
    "fold",
    "pour",
    "stir",
  ],
  "actions-d": [
    "wipe",
    "brush-teeth",
    "get-dressed",
    "put-away",
    "share",
    "wait",
    "choose",
    "playground",
    "beach",
    "tummy",
    "head",
    "coat",
    "jacket",
    "dress",
    "skirt",
    "garbage-truck",
  ],
  "objects-a": [
    "fire-truck",
    "police-car",
    "bus",
    "airplane",
    "bicycle",
    "pants",
    "shoes",
    "egg",
    "dog",
    "cow",
    "chicken",
    "fish",
    "boat",
    "cement-mixer",
    "dump-truck",
    "tow-truck",
  ],
  "objects-b": [
    "table",
    "wagon",
    "blocks",
    "toothpaste",
    "sweater",
    "pine-cone",
    "garden",
    "path",
    "stick",
    "seed",
    "pajamas",
    "rain-boots",
    "river",
    "lake",
    "sandbox",
    "trailer",
  ],
  "objects-c": [
    "yogurt",
    "porridge",
    "raspberry",
    "plum",
    "pumpkin",
    "mama",
    "papa",
    "aunt",
    "uncle",
    "cat",
    "plate",
    "door",
    "milk",
    "water",
    "sailboat",
    "snow",
  ],
} as const;
export const meaningVisuals: Record<string, { sheet: string; cell: number }> =
  {};
for (const [sheet, slugs] of Object.entries(meaningSheets))
  slugs.forEach((slug, cell) => {
    meaningVisuals[slug] = { sheet, cell };
  });
for (const [slug, reference] of Object.entries({
  car: "red",
  truck: "yellow",
  cup: "blue",
})) {
  meaningVisuals[slug] = meaningVisuals[reference];
}
export function meaningVisual(
  concept: Pick<Concept, "slug" | "categoryId" | "imageUrl" | "childId">,
) {
  if (
    concept.childId ||
    concept.imageUrl !== `/images/${concept.categoryId}/${concept.slug}.svg`
  )
    return null;
  return meaningVisuals[concept.slug] ?? null;
}
